name: Deploy Flask Docker Image to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: 'plated-monolith-421705'
          create_credentials_file: false
          workload_identity_provider: 'Mondelez MLOPS workflow identity'
          service_account: 'mondelez-mlops-spn@plated-monolith-421705.iam.gserviceaccount.com'
          audience: //iam.googleapis.com/projects/806804060677/locations/global/workloadIdentityPools/mondelez-mlops-workflow-identity/providers/mondelez-mlops-workflow-identity

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.1
        with:
          service_account_key: '7ff3cdb824294fbc5b75fa626356b8a72c771a1b'
          project_id: 'plated-monolith-421705'
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GKE_PROJECT}}/${{ secrets.FLASK_IMAGE_NAME}}:latest .
          docker push gcr.io/${{ secrets.GKE_PROJECT}}/${{ secrets.FLASK_IMAGE_NAME}}:latest

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials <CLUSTER_NAME> --zone <CLUSTER_ZONE>
          kubectl set image deployment/<DEPLOYMENT_NAME> <CONTAINER_NAME>=gcr.io/<YOUR_PROJECT_ID>/<IMAGE_NAME>:latest
