name: Deploy Flask Docker Image to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.1
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT}}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GKE_PROJECT}}/${{ secrets.FLASK_IMAGE_NAME}}:latest .
          docker push gcr.io/${{ secrets.GKE_PROJECT}}/${{ secrets.FLASK_IMAGE_NAME}}:latest

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials <CLUSTER_NAME> --zone <CLUSTER_ZONE>
          kubectl set image deployment/<DEPLOYMENT_NAME> <CONTAINER_NAME>=gcr.io/<YOUR_PROJECT_ID>/<IMAGE_NAME>:latest
